<?php

return [
    [
        'id' => 1,
        'slug' => 'trailz-summit-v1',
        'title' => 'Trailz: Summit v1',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 3999,
        'category' => 't-shirts',
        'description' => 'The Trailz Summit v1 is built as a soft cotton streetwear tee with a relaxed oversized fit for everyday comfort.',
        'details' => [
            'Relaxed oversized fit',
            'Soft cotton fabric',
            'Durable print finish',
            'Ribbed crew neck'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['1.jpg', '15.jpg', '16.jpg'],
        'trending' => true,
    ],
    [
        'id' => 2,
        'slug' => 'kanso-ze-blue',
        'title' => 'Kanso ZE: Blue',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 4499,
        'category' => 't-shirts',
        'description' => 'Minimalism meets everyday wear in the Kanso ZE Blue tee, with a clean graphic and easy oversized drape.',
        'details' => [
            'Minimalist graphic',
            'Premium cotton feel',
            'Comfortable daily fit',
            'Reinforced stitching'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['2.jpg', '1.jpg', '15.jpg'],
        'trending' => true,
    ],
    [
        'id' => 3,
        'slug' => 'ubz-ascend-mocha',
        'title' => 'UBZ Ascend: Mocha',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 5499,
        'category' => 't-shirts',
        'description' => 'Elevate your style with the UBZ Ascend Mocha tee, blending earthy tones with premium cotton for a sharp streetwear look.',
        'details' => [
            'Oversized streetwear fit',
            'Premium cotton fabric',
            'Mocha brown accents',
            'Soft hand feel'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['3.jpg', '17.jpg', '18.jpg'],
        'trending' => false,
    ],
    [
        'id' => 4,
        'slug' => 'slides-2-0-eclipse',
        'title' => 'Slides 2.0: Eclipse',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 2999,
        'category' => 't-shirts',
        'description' => 'The Slides 2.0 Eclipse redefined casual comfort. With a sleek all-black design and contoured footbed, it\'s the perfect companion for your off-duty days.',
        'details' => [
            'Easy everyday fit',
            'Soft neckline finish',
            'Fade-resistant graphic',
            'Signature logo detail'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['4.jpg', '2.jpg', '1.jpg'],
        'trending' => false,
    ],
    [
        'id' => 5,
        'slug' => 'ben-10-alien-force',
        'title' => 'Ben 10: Alien Force',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 4799,
        'category' => 't-shirts',
        'description' => 'Unleash your inner hero with the Ben 10 Alien Force edition. Bold green accents and a futuristic design inspired by the iconic series.',
        'details' => [
            'Limited edition artwork',
            'Breathable cotton fabric',
            'Bold print detailing',
            'Relaxed shoulder drop'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['5.jpg', '16.jpg', '1.jpg'],
        'trending' => true,
    ],
    [
        'id' => 6,
        'slug' => 'urban-blaze-blue-moon',
        'title' => 'Urban Blaze: Blue Moon',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 5299,
        'category' => 't-shirts',
        'description' => 'Ignite the streets with the Urban Blaze Blue Moon. A vibrant blue palette combined with aggressive design lines for the modern trendsetter.',
        'details' => [
            'Layered graphic artwork',
            'Breathable cotton fabric',
            'Structured collar',
            'Clean straight hem'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['6.jpg', '2.jpg', '15.jpg'],
        'trending' => true,
    ],
    [
        'id' => 7,
        'slug' => 'soft-step-low',
        'title' => 'Soft-Step Low',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 3499,
        'category' => 't-shirts',
        'description' => 'Elegance in every step. The Soft-Step Low for women features a delicate design with cloud-like cushioning for all-day comfort.',
        'details' => [
            'Relaxed silhouette',
            'Ultra-soft cotton',
            'Lightweight everyday feel',
            'Subtle pastel accents'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['7.jpg', '21.jpg', '22.jpg'],
        'trending' => false,
    ],
    [
        'id' => 8,
        'slug' => 'grace-oversized-tee',
        'title' => 'Grace Mid-Top',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 3999,
        'category' => 't-shirts',
        'description' => 'The Grace Mid-Top offers a balanced everyday tee fit that pairs easily with any outfit.',
        'details' => [
            'Dropped shoulder fit',
            'Supple cotton fabric',
            'Gold-tone graphic accents',
            'Easy all-day comfort'
        ],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['8.jpg', '22.jpg', '21.jpg'],
        'trending' => false,
    ],
    
    
    [
        'id' => 19,
        'slug' => 'neon-burst-19',
        'title' => 'Neon Burst 19',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 4999,
        'category' => 't-shirts',
        'description' => 'Make a statement with the Neon Burst 19. Vibrant colors meet a comfortable oversized tee design for the bold.',
        'details' => ['Neon accents', 'Soft cotton fabric', 'Relaxed fit', 'Durable print'],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['19.jpg', '20.jpg', '5.jpg'],
        'trending' => false,
    ],
    [
        'id' => 20,
        'slug' => 'arctic-chill-20',
        'title' => 'Arctic Chill 20',
        'subtitle' => 'Oversized T-Shirt',
        'price' => 4699,
        'category' => 't-shirts',
        'description' => 'Cool tones and premium comfort define the Arctic Chill 20. Perfect for everyday wear with a clean aesthetic.',
        'details' => ['Cool grey palette', 'Soft cotton panels', 'Relaxed drape', 'Lightweight feel'],
        'sizes' => ['S', 'M', 'L', 'XL', '2XL'],
        'images' => ['20.jpg', '19.jpg', '12.jpg'],
        'trending' => false,
    ],
    [
        'id' => 23,
        'slug' => 'no-show-stealth-socks',
        'title' => 'No-Show Stealth Socks',
        'subtitle' => 'Accessories',
        'price' => 399,
        'category' => 'socks',
        'description' => 'Soft everyday socks made from a high-quality cotton blend.',
        'details' => ['Soft cuff', 'Cotton blend', 'Breathable knit', 'Seamless toe'],
        'sizes' => ['M', 'L'],
        'images' => ['23.jpg', '24.jpg', '10.jpg'],
        'trending' => false,
    ],
    [
        'id' => 24,
        'slug' => 'performance-crew-socks',
        'title' => 'Performance Crew Socks',
        'subtitle' => 'Accessories',
        'price' => 599,
        'category' => 'socks',
        'description' => 'Built for performance. These crew socks provide extra cushioning and support for active lifestyles.',
        'details' => ['Extra cushioning', 'Moisture-wicking', 'Arch support', 'Durable knit'],
        'sizes' => ['M', 'L'],
        'images' => ['24.jpg', '23.jpg', '10.jpg'],
        'trending' => false,
    ],
    
];
