<?php

return [
    [
        'id' => 1,
        'slug' => 'trailz-summit-v1',
        'title' => 'Trailz: Summit v1',
        'subtitle' => 'Men Low Top Sneakers',
        'price' => 3999,
        'category' => 'low-top',
        'description' => 'The Trailz Summit v1 is engineered for both urban exploration and rugged trails. Featuring a high-grip outsole and premium breathable mesh, it offers unparalleled comfort and style.',
        'details' => [
            'Lightweight construction',
            'Breathable mesh upper',
            'High-traction rubber outsole',
            'Padded collar and tongue'
        ],
        'sizes' => [7, 8, 9, 10, 11],
        'images' => ['1.jpg', '15.jpg', '16.jpg'],
        'trending' => true,
    ],
    [
        'id' => 2,
        'slug' => 'kanso-ze-blue',
        'title' => 'Kanso ZE: Blue',
        'subtitle' => 'Men Low Top Sneakers',
        'price' => 4499,
        'category' => 'low-top',
        'description' => 'Minimalism meets performance in the Kanso ZE Blue. A clean silhouette combined with a deep navy hue makes it a versatile addition to any wardrobe.',
        'details' => [
            'Minimalist silhouette',
            'Premium suede overlays',
            'Responsive cushioning',
            'Durable cotton laces'
        ],
        'sizes' => [6, 7, 8, 9, 10],
        'images' => ['2.jpg', '1.jpg', '15.jpg'],
        'trending' => true,
    ],
    [
        'id' => 3,
        'slug' => 'ubz-ascend-mocha',
        'title' => 'UBZ Ascend: Mocha',
        'subtitle' => 'Men High Top Sneakers',
        'price' => 5499,
        'category' => 'high-top',
        'description' => 'Elevate your style with the UBZ Ascend Mocha. This high-top masterpiece blends earthy tones with premium leather for a sophisticated streetwear look.',
        'details' => [
            'High-top ankle support',
            'Premium full-grain leather',
            'Mocha brown accents',
            'Cushioned insole'
        ],
        'sizes' => [8, 9, 10, 11, 12],
        'images' => ['3.jpg', '17.jpg', '18.jpg'],
        'trending' => false,
    ],
    [
        'id' => 4,
        'slug' => 'slides-2-0-eclipse',
        'title' => 'Slides 2.0: Eclipse',
        'subtitle' => 'Men Low Top Sneakers',
        'price' => 2999,
        'category' => 'low-top',
        'description' => 'The Slides 2.0 Eclipse redefined casual comfort. With a sleek all-black design and contoured footbed, it\'s the perfect companion for your off-duty days.',
        'details' => [
            'Contoured footbed',
            'Synthetic leather strap',
            'Water-resistant finish',
            'Embossed logo detail'
        ],
        'sizes' => [7, 8, 9, 10, 11],
        'images' => ['4.jpg', '2.jpg', '1.jpg'],
        'trending' => false,
    ],
    [
        'id' => 5,
        'slug' => 'ben-10-alien-force',
        'title' => 'Ben 10: Alien Force',
        'subtitle' => 'Men Low Top Sneakers',
        'price' => 4799,
        'category' => 'low-top',
        'description' => 'Unleash your inner hero with the Ben 10 Alien Force edition. Bold green accents and a futuristic design inspired by the iconic series.',
        'details' => [
            'Limited edition colorway',
            'Synthetic mesh panels',
            'Reflective detailing',
            'TPU heel counter'
        ],
        'sizes' => [7, 8, 9, 10],
        'images' => ['5.jpg', '16.jpg', '1.jpg'],
        'trending' => true,
    ],
    [
        'id' => 6,
        'slug' => 'urban-blaze-blue-moon',
        'title' => 'Urban Blaze: Blue Moon',
        'subtitle' => 'Men Low Top Sneakers',
        'price' => 5299,
        'category' => 'low-top',
        'description' => 'Ignite the streets with the Urban Blaze Blue Moon. A vibrant blue palette combined with aggressive design lines for the modern trendsetter.',
        'details' => [
            'Multi-layered upper',
            'Breathable fabric lining',
            'Enhanced arch support',
            'Non-marking outsole'
        ],
        'sizes' => [6, 7, 8, 9, 10, 11],
        'images' => ['6.jpg', '2.jpg', '15.jpg'],
        'trending' => true,
    ],
    [
        'id' => 7,
        'slug' => 'soft-step-low',
        'title' => 'Soft-Step Low',
        'subtitle' => 'Women Low Top Sneakers',
        'price' => 3499,
        'category' => 'women-low',
        'description' => 'Elegance in every step. The Soft-Step Low for women features a delicate design with cloud-like cushioning for all-day comfort.',
        'details' => [
            'Feminine silhouette',
            'Ultra-soft cushioning',
            'Lightweight EVA midsole',
            'Subtle pastel accents'
        ],
        'sizes' => [5, 6, 7, 8, 9],
        'images' => ['7.jpg', '21.jpg', '22.jpg'],
        'trending' => false,
    ],
    [
        'id' => 8,
        'slug' => 'grace-mid-top',
        'title' => 'Grace Mid-Top',
        'subtitle' => 'Women Mid Top Sneakers',
        'price' => 3999,
        'category' => 'women-mid',
        'description' => 'The Grace Mid-Top offers a perfect balance of style and support. A versatile mid-height sneaker that pairs beautifully with any outfit.',
        'details' => [
            'Mid-cut ankle collar',
            'Supple leather upper',
            'Gold-tone hardware',
            'Ortholite insole'
        ],
        'sizes' => [5, 6, 7, 8, 9],
        'images' => ['8.jpg', '22.jpg', '21.jpg'],
        'trending' => false,
    ],
    
    
    [
        'id' => 19,
        'slug' => 'neon-burst-19',
        'title' => 'Neon Burst 19',
        'subtitle' => 'Men Mid Top Sneakers',
        'price' => 4999,
        'category' => 'mid-top',
        'description' => 'Make a statement with the Neon Burst 19. Vibrant colors meet a comfortable mid-top design for the bold.',
        'details' => ['Neon accents', 'Synthetic overlays', 'Cushioned ankle', 'High-grip tread'],
        'sizes' => [7, 8, 9, 10, 11],
        'images' => ['19.jpg', '20.jpg', '5.jpg'],
        'trending' => false,
    ],
    [
        'id' => 20,
        'slug' => 'arctic-chill-20',
        'title' => 'Arctic Chill 20',
        'subtitle' => 'Men Mid Top Sneakers',
        'price' => 4699,
        'category' => 'mid-top',
        'description' => 'Cool tones and premium comfort define the Arctic Chill 20. Perfect for everyday wear with a clean aesthetic.',
        'details' => ['Cool grey palette', 'Suede panels', 'Memory foam insole', 'Lightweight sole'],
        'sizes' => [8, 9, 10, 11],
        'images' => ['20.jpg', '19.jpg', '12.jpg'],
        'trending' => false,
    ],
    [
        'id' => 23,
        'slug' => 'no-show-stealth-socks',
        'title' => 'No-Show Stealth Socks',
        'subtitle' => 'Accessories',
        'price' => 399,
        'category' => 'socks',
        'description' => 'Invisible comfort for your low-top sneakers. High-quality cotton blend with a non-slip heel grip.',
        'details' => ['Non-slip heel', 'Cotton blend', 'Breathable knit', 'Seamless toe'],
        'sizes' => ['M', 'L'],
        'images' => ['23.jpg', '24.jpg', '10.jpg'],
        'trending' => false,
    ],
    [
        'id' => 24,
        'slug' => 'performance-crew-socks',
        'title' => 'Performance Crew Socks',
        'subtitle' => 'Accessories',
        'price' => 599,
        'category' => 'socks',
        'description' => 'Built for performance. These crew socks provide extra cushioning and support for active lifestyles.',
        'details' => ['Extra cushioning', 'Moisture-wicking', 'Arch support', 'Durable knit'],
        'sizes' => ['M', 'L'],
        'images' => ['24.jpg', '23.jpg', '10.jpg'],
        'trending' => false,
    ],
    
];
